SBP: Installing Fujitsu Enterprise Postgres on SUSE Linux Enterprise Server for IBM Z and LinuxONE - Getting Started
SUSE/suse-best-practices pull request #203
Opened 2021-05-21 17:13 UTC by mfriesenegger

2021-05-24 15:59 UTC, cjschroder requested changes
This looks good, Mike, well-organized and clear. I found only a few small typos.

2021-05-24 15:59 UTC, cjschroder commented on adoc/TRD-fep-vm-sles-s390x-getting-started.adoc
> +The goal of this chapter is to successfully install SLES 12 SP5.  To accomplish this the VM is started and the autoyast installation begins automatically.
autoyast -> AutoYAST

2021-05-24 15:59 UTC, cjschroder commented on adoc/TRD-fep-vm-sles-s390x-getting-started.adoc
> +NOTE: You can safely ignore any postfix warnings or errors that appear in the console.
postfix -> Postfix

2021-05-24 15:59 UTC, cjschroder commented on adoc/TRD-fep-vm-sles-s390x-getting-started.adoc
> +NOTE: The systemctl service name for FEP 12 is FSEPWAD_120_WA_64.service
FSEPWAD looks like a name teenagers insult each other with :)

2021-05-24 15:59 UTC, cjschroder commented on adoc/TRD-fep-vm-sles-s390x-getting-started.adoc
> +* A workstation with a web browser and ssh client will be needed.
web -> Web, ssh -> SSH

2021-05-24 20:44 UTC, cjschroder commented
I see I missed a few typos. Arg. :frowning_face: 
Today is a German holiday, I will leave this for Meike to review when she returns.

2021-05-24 20:44 UTC, cjschroder approved these changes

2021-05-25 13:23 UTC, chabowski commented
Thanks @cjschroder and @mfriesenegger - I'll take if from here. Will merge the PR now and have final check /fix typos.
Thanks again!

2021-05-25 13:23 UTC, merged

2021-05-25 16:08 UTC, chabowski commented
Final (??) PDF version of the paper for your review:
[TRD-fep-vm-sles-s390x-getting-started_color_en.pdf](https://github.com/SUSE/suse-best-practices/files/6540772/TRD-fep-vm-sles-s390x-getting-started_color_en.pdf)

2021-05-25 16:23 UTC, mfriesenegger commented
The PDF looks like it has all of the final edits.

2021-05-25 17:23 UTC, chabowski commented
New PDF with non-working link :-) as discussed: 
[TRD-fep-vm-sles-s390x-getting-started_color_en.pdf](https://github.com/SUSE/suse-best-practices/files/6541216/TRD-fep-vm-sles-s390x-getting-started_color_en.pdf)