Update MAIN-SBP-AMD-EPYC-4-SLES15SP4.xml
SUSE/suse-best-practices pull request #329
Opened 2022-10-21 08:39 UTC by dariavladykina

2022-10-24 16:35 UTC, chabowski commented on xml/MAIN-SBP-AMD-EPYC-4-SLES15SP4.xml
> +	OpenMP to take advantage of multiple memory controllers. The array of elements for
`The array elements for the benchmark were set at 268,435,456 elements at compile time`

array element is a fix term

2022-10-24 16:42 UTC, chabowski requested changes
Thanks Daria, for the very thorough language review! I only found one tiny little thing that needs to be changed. Let me know if I should change it or if you would like to do it. 

Thought I had caught all "processors" in the context of AMD EPYC that had not been capitalized  - but seems I did forget to apply the changes LOL. Thanks again!

2022-10-25 10:27 UTC, dariavladykina reviewed
Apply review suggestions

2022-10-25 10:27 UTC, dariavladykina commented on xml/MAIN-SBP-AMD-EPYC-4-SLES15SP4.xml
> +	OpenMP to take advantage of multiple memory controllers. The array of elements for
```suggestion
	OpenMP to take advantage of multiple memory controllers. The array elements for
```

2022-10-25 10:38 UTC, dariavladykina commented on xml/MAIN-SBP-AMD-EPYC-4-SLES15SP4.xml
>  	OpenMP to take advantage of multiple memory controllers. The array elements for
```suggestion
	OpenMP to take advantage of multiple memory controllers. The array of elements for
```

2022-10-25 10:49 UTC, chabowski approved these changes

2022-10-25 10:50 UTC, merged